In [2]:
import numpy as np
import pandas as pd
import jieba
import re

# 导入数据
df = pd.read_csv('adjusted_RandomForestClassifier.csv')

In [3]:
df

Unnamed: 0                                            message  \
0               0                                    连个鼠标垫都没有，抠门扣到家了   
1               1                                 刚买两天就降价，多买个鼠标还不能保价   
2               2                                新电脑刚买的   系统更新下 就这样了   
3               3                                        还不到十天就降价。厉害   
4               4                                         刚买完就降了两百块钱   
...           ...                                                ...   
54995       54995  第一次买华为电脑,开机很流畅,第一次的开始设置很友好,不用想太多,直接跟着默认设置,很快就把...   
54996       54996                                      电脑运行速度很快，外形好看   
54997       54997                           笔记本的外观很漂亮，拿到手里很有分量，做工很精细   
54998       54998                                      外观很是不错，键盘手感很好   
54999       54999                                 本子收到了，物流超快。宝贝用着不错。   

       sentiment                                            content  \
0              1                                        鼠标垫 抠门 扣到 家   
1              1                                 刚买 两天 降价 多买个 鼠标 保价   
2              1                                        电脑 刚买 系统 更新   
3              1                                        不到 十天 降价 厉害   
4              1                                       刚买 完 降 两百块 钱   
...          ...                                                ...   
54995          0  第一次 买 华为 电脑 开机 流畅 第一次 设置 友好 不用 想太多 跟着 默认设置 很快 ...   
54996          0                                  电脑 运行 速度 很快 外形 好看   
54997          0                          笔记本 外观 很漂亮 拿到 手里 分量 做工 精细   
54998          0                                      外观 不错 键盘 手感 好   
54999          0                                  本子 收到 物流 超快 宝贝 不错   

       0 probability  1 probability  predict  
0           0.128603       0.871397        1  
1           0.000000       1.000000        1  
2           0.021998       0.978002        1  
3           0.007320       0.992680        1  
4           0.029705       0.970295        1  
...              ...            ...      ...  
54995       1.000000       0.000000        0  
54996       1.000000       0.000000        0  
54997       1.000000       0.000000        0  
54998       0.920000       0.080000        0  
54999       1.000000       0.000000        0  

[55000 rows x 7 columns]

In [4]:
zh_pattern = re.compile(u'[\u4e00-\u9fa5]+')
stop_word = [line.strip() for line in open ('chineseStopWords.txt','r').readlines()]
def extract_words(word):
    word = str(word).strip()
    zh_word = re.findall(zh_pattern,word)
    lst = jieba.cut(''.join(zh_word))
    final_word = [char for char in lst if char not in stop_word]
    return ' '.join(final_word) #空格隔开
data_e = df['message'].apply(lambda x:extract_words(x))   #对整列进行操作
data_extract = pd.DataFrame(data_e.values,columns=['content'])  #转换成列表

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\28772\AppData\Local\Temp\jieba.cache
Loading model cost 0.642 seconds.
Prefix dict has been built successfully.


In [5]:
cts = []
for i in data_extract['content']:
    cts.append(i)
cts

['鼠标垫 抠门 扣到 家',
 '刚买 两天 降价 多买个 鼠标 保价',
 '电脑 刚买 系统 更新',
 '不到 十天 降价 厉害',
 '刚买 完 降 两百块 钱',
 '播放 音乐 声音 时大时 无声',
 '刚买 十二天 降 块钱 充电器',
 '蹭 退换 还要 检测 工作日内 呵呵',
 '变动 建议 入手 斯伍 叉叉',
 '买 一个月 闪屏 换 电脑 漏电',
 '不好 发热 烫手 价格 买贵',
 '充电 滋滋 声 影响 效果',
 '不到 一个月 开 不了 机了',
 '发过来 钢化 膜 差点 碎成 渣',
 '没 配送 送货上门',
 '买 不到 一个月 骤 降价 保天',
 '到手 几天 连续 死机 次',
 '电脑 慢 买回来 污垢',
 '客服 服务态度 不好 发消息 不回',
 '电源适配器 差 插头',
 '刚买 不到 降价 挺 惨',
 '手提包',
 '货物 检查 发货',
 '收货 降价 质量',
 '几天 降价 买 寂寞',
 '一个月 降 一千 保值',
 '第二天 莫名其妙 不了 机',
 '客服 承认 商品 页面 保价',
 '增值 服务 分开 配送 提示 好',
 '买 多久 降 转轴 感觉 不行 异响',
 '刚买 几天 降价 块 申请 保价 保价 期限',
 '电脑 磕坏 联想 破品 控',
 '裸机 电脑包 没',
 '屏幕 黑色 状态 下边 上漏 白光',
 '说好 赠品 收到',
 '帮别人 买 买 完 降价 元真 没',
 '电脑 充电器',
 '刚买 完 降价 京东 一生 黑',
 '两周 时间 下降 块 速度 两周 卖块 买 小伙伴 赶紧 两周',
 '刚买 完 降价 二百 体验 差',
 '点开 设置 卡',
 '办公 轻薄 家庭 个人版',
 '刚买 两天 开 不了 机了 啃 爹',
 '双十 预售 抢购 双 十二 降价 三百多',
 '休眠 指纹 密码 系统',
 '少 寄 东西 三包 凭证',
 '没多久 电脑 重启 设备',
 '商品 本身 好 活动 狗',
 '买 不到 一个月 降价 点 好',
 '两天 开 不了 机了',
 '买 不到 一个月 降 保价',
 '号 买 一看 降价',
 '速度 行 价格 高 点',
 '充电 键盘 电流',
 '买 回 半个 机器 高温 报警 只能 售

In [6]:
# TFIDF
from sklearn.feature_extraction.text import TfidfVectorizer

# 使用模型
vectorizer = TfidfVectorizer(max_features=700,max_df=0.5,smooth_idf=True)
X = vectorizer.fit_transform(cts)
X.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.39258868,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [31]:
vectorizer.vocabulary_

{'刚买': 103,
 '两天': 40,
 '降价': 655,
 '鼠标': 698,
 '电脑': 462,
 '系统': 514,
 '更新': 369,
 '不到': 22,
 '厉害': 127,
 '声音': 174,
 '充电器': 81,
 '还要': 620,
 '建议': 253,
 '入手': 82,
 '一个月': 0,
 '不好': 27,
 '发热': 138,
 '烫手': 436,
 '价格': 60,
 '充电': 80,
 '影响': 265,
 '效果': 341,
 '不了': 21,
 '配送': 640,
 '到手': 106,
 '几天': 92,
 '买回来': 47,
 '客服': 224,
 '服务态度': 374,
 '检查': 399,
 '发货': 139,
 '质量': 587,
 '第二天': 500,
 '商品': 156,
 '服务': 373,
 '提示': 327,
 '感觉': 293,
 '不行': 33,
 '联想': 537,
 '电脑包': 463,
 '屏幕': 240,
 '黑色': 697,
 '赠品': 591,
 '收到': 338,
 '京东': 52,
 '时间': 358,
 '速度': 636,
 '赶紧': 594,
 '体验': 66,
 '设置': 577,
 '办公': 111,
 '轻薄': 613,
 '双十': 132,
 '预售': 674,
 '指纹': 314,
 '东西': 37,
 '设备': 576,
 '活动': 415,
 '键盘': 652,
 '半个': 120,
 '机器': 382,
 '只能': 140,
 '售后': 153,
 '亮点': 54,
 '退货': 629,
 '运行': 615,
 '打开': 302,
 '网页': 529,
 '启动': 149,
 '赠送': 592,
 '坏点': 170,
 '很快': 272,
 '正好': 404,
 '希望': 245,
 '画面': 466,
 '买来': 48,
 '漏光': 430,
 '开盖': 258,
 '两个': 39,
 '实在': 219,
 '购买': 588,
 '打字': 301,
 '好评': 205,
 '很棒': 273,
 '散热

In [33]:
# 奇异值分解
from sklearn.decomposition import TruncatedSVD

#实例化、训练
svd_model = TruncatedSVD(n_components=5,algorithm='randomized',n_iter=100,random_state=32451)
X_topic = svd_model.fit_transform(X)
X_topic

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.01293875, -0.03884784,  0.02083741,  0.00856079, -0.00616269],
       [ 0.05166961, -0.14313037,  0.12149   ,  0.1164325 ,  0.00563455],
       ...,
       [ 0.1016567 , -0.06250658, -0.06852756, -0.05833246, -0.07509128],
       [ 0.21760094, -0.13686908, -0.27623879,  0.14001265,  0.09404754],
       [ 0.08894486, -0.15574128, -0.07249152, -0.0269889 ,  0.12847733]])

In [24]:
terms = vectorizer.get_feature_names()

C:\Users\28772\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [34]:
for i in range(5):
    # 取出主题词权重
    comp = svd_model.components_[i]
    # 转化字典
    dz = dict(zip(terms,comp))
    dz_s = sorted(dict(zip(terms,comp)).items(),key=lambda x:x[1],reverse=True)[:10]
    print('Topic' +str(i)+':'+' '.join([d[0]for d in dz_s]))

Topic0:速度 运行 屏幕 散热 外观 效果 轻薄 外形 性能 不错
Topic1:散热 效果 外形 程度 性能 轻薄 外观 屏幕 运行 特色
Topic2:电脑 很快 速度 运行 喜欢 收到 好看 外形 程度 开机
Topic3:电脑 不错 性能 散热 效果 屏幕 感觉 外形 联想 配置
Topic4:不错 很快 速度 开机 物流 运行 散热 机箱 包装 电脑


### 总结

In [35]:
np.argmax(X_topic,axis=1)

array([0, 2, 2, ..., 0, 0, 4], dtype=int64)

In [28]:
# 计算每个文本属于哪个主题
np.argmax(X_topic,axis=1)
keywords = []
for i in np.argmax(X_topic,axis=1):
    comp = svd_model.components_[int(i)]
    # 转化字典
    dz = dict(zip(terms,comp))
    dz_s = sorted(dict(zip(terms,comp)).items(),key=lambda x:x[1],reverse=True)[:10]
    keywords.append(' '.join([d[0]for d in dz_s]))

In [22]:
keywords

['速度 运行 屏幕 散热 外观 效果 轻薄 外形 性能 不错',
 '电脑 很快 速度 运行 喜欢 收到 好看 外形 程度 开机',
 '电脑 很快 速度 运行 喜欢 收到 好看 外形 程度 开机',
 '速度 运行 屏幕 散热 外观 效果 轻薄 外形 性能 不错',
 '电脑 很快 速度 运行 喜欢 收到 好看 外形 程度 开机',
 '速度 运行 屏幕 散热 外观 效果 轻薄 外形 性能 不错',
 '速度 运行 屏幕 散热 外观 效果 轻薄 外形 性能 不错',
 '速度 运行 屏幕 散热 外观 效果 轻薄 外形 性能 不错',
 '速度 运行 屏幕 散热 外观 效果 轻薄 外形 性能 不错',
 '电脑 不错 性能 散热 效果 屏幕 感觉 外形 联想 配置',
 '速度 运行 屏幕 散热 外观 效果 轻薄 外形 性能 不错',
 '速度 运行 屏幕 散热 外观 效果 轻薄 外形 性能 不错',
 '速度 运行 屏幕 散热 外观 效果 轻薄 外形 性能 不错',
 '速度 运行 屏幕 散热 外观 效果 轻薄 外形 性能 不错',
 '速度 运行 屏幕 散热 外观 效果 轻薄 外形 性能 不错',
 '速度 运行 屏幕 散热 外观 效果 轻薄 外形 性能 不错',
 '速度 运行 屏幕 散热 外观 效果 轻薄 外形 性能 不错',
 '电脑 很快 速度 运行 喜欢 收到 好看 外形 程度 开机',
 '电脑 很快 速度 运行 喜欢 收到 好看 外形 程度 开机',
 '速度 运行 屏幕 散热 外观 效果 轻薄 外形 性能 不错',
 '速度 运行 屏幕 散热 外观 效果 轻薄 外形 性能 不错',
 '速度 运行 屏幕 散热 外观 效果 轻薄 外形 性能 不错',
 '不错 很快 速度 开机 物流 运行 散热 机箱 包装 电脑',
 '速度 运行 屏幕 散热 外观 效果 轻薄 外形 性能 不错',
 '速度 运行 屏幕 散热 外观 效果 轻薄 外形 性能 不错',
 '电脑 不错 性能 散热 效果 屏幕 感觉 外形 联想 配置',
 '不错 很快 速度 开机 物流 运行 散热 机箱 包装 电脑',
 '电脑 很快 速度 运行 喜欢 收到 好看 外形 程度 开机',
 '速度 运行 屏幕 散热 外观 效果 轻薄 外形 性能 不错',
 '速度 运行 屏幕 散热 

In [30]:
df['LSA_Topic'] = np.argmax(X_topic,axis=1)
df['LSA_Keywords'] = keywords
df.to_csv('LSAResult.csv',index=0,columns=None,encoding='utf_8')
df

Unnamed: 0                                            message  \
0               0                                    连个鼠标垫都没有，抠门扣到家了   
1               1                                 刚买两天就降价，多买个鼠标还不能保价   
2               2                                新电脑刚买的   系统更新下 就这样了   
3               3                                        还不到十天就降价。厉害   
4               4                                         刚买完就降了两百块钱   
...           ...                                                ...   
54995       54995  第一次买华为电脑,开机很流畅,第一次的开始设置很友好,不用想太多,直接跟着默认设置,很快就把...   
54996       54996                                      电脑运行速度很快，外形好看   
54997       54997                           笔记本的外观很漂亮，拿到手里很有分量，做工很精细   
54998       54998                                      外观很是不错，键盘手感很好   
54999       54999                                 本子收到了，物流超快。宝贝用着不错。   

       sentiment                                            content  \
0              1                                        鼠标垫 抠门 扣到 家   
1              1                                 刚买 两天 降价 多买个 鼠标 保价   
2              1                                        电脑 刚买 系统 更新   
3              1                                        不到 十天 降价 厉害   
4              1                                       刚买 完 降 两百块 钱   
...          ...                                                ...   
54995          0  第一次 买 华为 电脑 开机 流畅 第一次 设置 友好 不用 想太多 跟着 默认设置 很快 ...   
54996          0                                  电脑 运行 速度 很快 外形 好看   
54997          0                          笔记本 外观 很漂亮 拿到 手里 分量 做工 精细   
54998          0                                      外观 不错 键盘 手感 好   
54999          0                                  本子 收到 物流 超快 宝贝 不错   

       0 probability  1 probability  predict  LSA_Topic  \
0           0.128603       0.871397        1          0   
1           0.000000       1.000000        1          2   
2           0.021998       0.978002        1          2   
3           0.007320       0.992680        1          0   
4           0.029705       0.970295        1          2   
...              ...            ...      ...        ...   
54995       1.000000       0.000000        0          0   
54996       1.000000       0.000000        0          0   
54997       1.000000       0.000000        0          0   
54998       0.920000       0.080000        0          0   
54999       1.000000       0.000000        0          0   

                        LSA_Keywords  
0      速度 运行 屏幕 散热 外观 效果 轻薄 外形 性能 不错  
1      电脑 很快 速度 运行 喜欢 收到 好看 外形 程度 开机  
2      电脑 很快 速度 运行 喜欢 收到 好看 外形 程度 开机  
3      速度 运行 屏幕 散热 外观 效果 轻薄 外形 性能 不错  
4      电脑 很快 速度 运行 喜欢 收到 好看 外形 程度 开机  
...                              ...  
54995  速度 运行 屏幕 散热 外观 效果 轻薄 外形 性能 不错  
54996  速度 运行 屏幕 散热 外观 效果 轻薄 外形 性能 不错  
54997  速度 运行 屏幕 散热 外观 效果 轻薄 外形 性能 不错  
54998  速度 运行 屏幕 散热 外观 效果 轻薄 外形 性能 不错  
54999  速度 运行 屏幕 散热 外观 效果 轻薄 外形 性能 不错  

[55000 rows x 9 columns]

In [23]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
xs = pca.fit_transform(X_topic)
xs

array([[-0.13400919, -0.07353569],
       [-0.14871759, -0.046639  ],
       [-0.17411527,  0.11428338],
       ...,
       [-0.10051914, -0.10822333],
       [-0.04328001, -0.04492516],
       [-0.15604083,  0.01441321]])

In [15]:
ds = pd.DataFrame(xs)
ds['label']=np.argmax(X_topic,axis=1)
ds

NameError: name 'xs' is not defined

In [14]:
import matplotlib.pyplot as plt
labels = list(set(list(ds['label'])))
colors = ['skyblue','tomato','pink','purple','red','green','brown','yellow','gold','orange']
for i in range(len(labels)):
    ds_ = ds[ds['label']==labels[i]]
    plt.plot(ds_[0],ds_[1],'o',color = colors[i])
plt.show()

NameError: name 'ds' is not defined